name: crm_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  google_fonts: ^6.2.1
  lucide_icons_flutter: any
  hugeicons: ^1.1.6
  animations: ^2.0.11
  fl_chart: ^0.66.2
  intl: ^0.19.0
  pdf: ^3.11.1
  printing: ^5.13.2
  url_launcher: ^6.3.0
  file_picker: ^8.0.0
  http: ^1.2.1
  image_picker: ^1.2.2
  path_provider: ^2.1.2
  image_cropper: ^12.2.1
  shared_preferences: ^2.5.5
  connectivity_plus: ^6.1.5
  internet_connection_checker: ^3.0.1
  google_mlkit_text_recognition: ^0.15.1
  open_filex: ^4.5.0
  dropdown_button2: ^3.1.0
  syncfusion_flutter_pdfviewer: ^33.2.12
  flutter_svg: ^2.3.0
  firebase_core: ^4.11.0
  firebase_messaging: ^16.4.1
  flutter_local_notifications: ^22.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.7
flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/WE CRM logo .png"
  remove_alpha_ios: true
  min_sdk_android: 21
flutter:
  uses-material-design: true
  assets:
    - assets/WE CRM logo .png
    - assets/chart.png
    - assets/Chatbackground.png
    - assets/google.png
    - assets/sdlogo.png
    - assets/fonts/
    - assets/images/
    - assets/Client/dbs.png
    - assets/Client/hcl_tech.png
    - assets/Client/idfc_bank.png
    - assets/Client/logo6.png
    - assets/Client/pvr.png
    - assets/Client/softrate.png
    - assets/Client/whatsapp_image.jpeg
    - assets/json/
    - assets/icons/
  fonts:
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit-VariableFont_wght.ttf
flutter_native_splash:
  color: "#ffffff"
  image: "assets/images/splash_screen3.jpg"
  android_12:
    color: "#ffffff"
    image: "assets/images/splash_screen3.jpg"
