import 'package:flutter/material.dart';
import 'package:hugeicons/hugeicons.dart';
import 'package:lucide_icons_flutter/lucide_icons.dart';

final List<Map<String, dynamic>> kAvailableServices = [
  {
    'title': 'Private Limited Incorporation',
    'subtitle': 'Complete company incorporation with name approval, DSC, DIN, and MCA filing.',
    'description': 'Complete company incorporation with name approval, DSC, DIN, and MCA filing.',
    'icon': HugeIcons.strokeRoundedOffice,
    'color': const Color(0xFF6366F1),
    'category': 'Incorporation',
    'averageWorkingDays': '7–10 days',
      'documentsRequired': ['Directors Aadhar & PAN Card', 'EB Bill < 2 months'],
    'features': ['Drafting AOA & MOA', 'Certificate of Incorporation (COI)', 'Corporate Identification Number (CIN)', 'PAN & TAN', 'Director Identification Numbers (DINs)', 'Digital Signature Certificates (DSCs)', 'Corporate Bank Setup support'],
  },
  {
    'title': 'LLP Incorporation',
    'subtitle': 'Register your LLP with name approval, incorporation, PAN, and MCA filing.',
    'description': 'Register your LLP with name approval, incorporation, PAN, and MCA filing.',
    'icon': HugeIcons.strokeRoundedBriefcase01,
    'color': const Color(0xFFF59E0B),
    'category': 'Incorporation',
    'averageWorkingDays': '7–10 days',
      'documentsRequired': ['Partners Aadhar & PAN Card', 'EB Bill < 2 months'],
    'features': ['Drafting & Registration of LLP Agreement', 'Certificate of Incorporation (COI)', 'LLP Identification Number (LLPIN)', 'PAN & TAN', 'Designated Partner Identification Numbers (DPINs)', 'Digital Signature Certificates (DSCs)', 'Corporate Bank Setup support'],
  },
  {
    'title': 'OPC Incorporation',
    'subtitle': 'Register your One Person Company with complete MCA incorporation support.',
    'description': 'Register your One Person Company with complete MCA incorporation support.',
    'icon': HugeIcons.strokeRoundedUser,
    'color': const Color(0xFF10B981),
    'category': 'Incorporation',
    'averageWorkingDays': '7–10 days',
      'documentsRequired': ['Director & Nominee Aadhar & PAN Card', 'EB Bill < 2 months'],
    'features': ['Nominee Appointment Documentation', 'Certificate of Incorporation (COI)', 'Corporate Identification Number (CIN)', 'PAN & TAN', 'Director Identification Numbers (DINs)', 'Digital Signature Certificates (DSCs)', 'Drafting AOA & MOA Corporate Bank Setup support'],
  },
  {
    'title': 'MSME Registration',
    'subtitle': 'Obtain Udyam Registration to access MSME benefits and business recognition.',
    'description': 'Obtain Udyam Registration to access MSME benefits and business recognition.',
    'icon': LucideIcons.medal,
    'color': const Color(0xFFF59E0B),
    'category': 'Incorporation',
    'averageWorkingDays': '1–2 days',
      'documentsRequired': ['Aadhar & PAN Card', 'Bank account details', 'EB Bill < 2 months'],
    'features': ['Udyam Registration Certificate', 'Priority Sector Lending Support', 'Collateral Free Loan Support', 'IP Reimbursement Advisory'],
  },
  {
    'title': 'Proprietorship Registration',
    'subtitle': 'Start your sole proprietorship with essential business registration support.',
    'description': 'Start your sole proprietorship with essential business registration support.',
    'icon': HugeIcons.strokeRoundedUser,
    'color': const Color(0xFF3B82F6),
    'category': 'Incorporation',
    'averageWorkingDays': '5–7 days',
    'features': ['Documentation support'],
  },
  {
    'title': 'MCA Compliance',
    'subtitle': 'Complete annual ROC filings and MCA compliance for your company.',
    'description': 'Complete annual ROC filings and MCA compliance for your company.',
    'icon': HugeIcons.strokeRoundedTask01,
    'color': const Color(0xFF14B8A6),
    'category': 'Compliance',
    'averageWorkingDays': 'On time',
      'documentsRequired': ['Last Year Bank Statements', 'All Company documents'],
    'features': ['Auditor appointment', '360° Accounting & Bookkeeping', 'Statutory Auditing', 'AOC 4 & MGT 7 filing', 'Director KYC', 'AGM & Notice', 'ITR filing'],
  },
  {
    'title': 'TDS Return Filing',
    'subtitle': 'Prepare and file TDS returns with corrections and certificate generation.',
    'description': 'Prepare and file TDS returns with corrections and certificate generation.',
    'icon': HugeIcons.strokeRoundedCalculator,
    'color': const Color(0xFF8B5CF6),
    'category': 'Compliance',
    'averageWorkingDays': '2–4 days',
      'documentsRequired': ['TAN & PAN', 'Salary Details', 'Previous TDS Return / RPU File (if available)', 'Valid Digital Signature'],
    'features': ['TDS Computation', 'Quarterly Return Filing', 'Form 16/16A Generation', 'Challan Payment', 'Notice Reply'],
  },
  {
    'title': 'PF Registration & Compliance',
    'subtitle': 'Complete PF registration with employee enrollment and monthly compliance.',
    'description': 'Complete PF registration with employee enrollment and monthly compliance.',
    'icon': HugeIcons.strokeRoundedDocumentValidation,
    'color': const Color(0xFF3B82F6),
    'category': 'Compliance',
    'averageWorkingDays': '5–7 days',
      'documentsRequired': ['Employee Master Details', 'PF Contribution Details', 'Employee KYC Details', 'Bank Account Details'],
    'features': ['PF Registration', 'Monthly ECR Filing', 'Challan Generation', 'Employee Addition/Deletion', 'KYC Updates'],
  },
  {
    'title': 'Trademark Registration',
    'subtitle': 'Protect your business name, logo, and brand through trademark registration.',
    'description': 'Protect your business name, logo, and brand through trademark registration.',
    'icon': HugeIcons.strokeRoundedTradeMark,
    'color': const Color(0xFFEC4899),
    'category': 'IP',
    'averageWorkingDays': '5–7 days',
    'documentsRequired': ['Trademark Logo', 'MSME Certificate'],
    'features': ['Trademark Search', 'Application Filing', 'Registration Certificate', 'Reimbursement Advisory'],
  },
  {
    'title': 'Copyright Registration',
    'subtitle': 'Register your original creative work with official copyright protection.',
    'description': 'Register your original creative work with official copyright protection.',
    'icon': LucideIcons.copyright,
    'color': const Color(0xFF6366F1),
    'category': 'IP',
    'averageWorkingDays': '12–15 days',
    'documentsRequired': ['Identity Proof of Applicant', 'Details of the Copyright Work'],
    'features': ['Diary Number Generation', 'Application Filing', 'Work Submission', 'Copyright Certificate'],
  },
  {
    'title': 'Patent Registration',
    'subtitle': 'Secure legal protection for your invention through professional patent filing.',
    'description': 'Secure legal protection for your invention through professional patent filing.',
    'icon': LucideIcons.lightbulb,
    'color': const Color(0xFFF59E0B),
    'category': 'IP',
    'averageWorkingDays': '12–15 days',
      'documentsRequired': ['Company Registration Documents', 'Details of the Invention', 'Technical Documents'],
    'features': ['Patent Search', 'Provisional Drafting', 'Complete Specification', 'Examination Reply', 'Patent Grant'],
  },
  {
    'title': 'Income Tax Return (ITR)',
    'subtitle': 'Income Tax Return filing for individuals and businesses.',
    'description': 'Income Tax Return filing for individuals and businesses.',
    'icon': HugeIcons.strokeRoundedCalculate,
    'color': const Color(0xFF8B5CF6),
    'category': 'Tax',
    'averageWorkingDays': '1–3 days',
    'documentsRequired': ['Last Year Bank Statements', 'All Company documents'],
    'features': ['Income Computation', 'Tax Saving Advisory', 'Return Filing (ITR 1-7)', 'Refund Tracking', 'Assessment Support'],
  },
  {
    'title': 'GST Registration',
    'subtitle': 'Register for GST and receive your GSTIN with complete filing support.',
    'description': 'Register for GST and receive your GSTIN with complete filing support.',
    'icon': HugeIcons.strokeRoundedLicenseDraft,
    'color': const Color(0xFF10B981),
    'category': 'Tax',
    'averageWorkingDays': '5–7 days',
      'documentsRequired': ['Aadhaar & PAN Card', 'Recent Photograph of the applicant', 'Proof of Principal Place of Business', 'Cancelled Cheque or Bank Statement'],
    'features': ['GST Application Filing', 'Document Verification', 'ARN Generation', 'Clarification Support', 'GSTIN Certificate'],
  },
  {
    'title': 'GST Returns Filing',
    'subtitle': 'File monthly or quarterly GST returns with accurate reconciliation support.',
    'description': 'File monthly or quarterly GST returns with accurate reconciliation support.',
    'icon': HugeIcons.strokeRoundedCalculate,
    'color': const Color(0xFF3B82F6),
    'category': 'Tax',
    'averageWorkingDays': '1–3 days',
    'features': ['GSTR-1 & 3B Filing', 'GSTR-2A/2B Reconciliation', 'Input Tax Credit (ITC)', 'Annual Return GSTR-9', 'Audit Support'],
  },
  {
    'title': 'GST Cancellation',
    'subtitle': 'Cancel your GST registration with proper filing and legal compliance.',
    'description': 'Cancel your GST registration with proper filing and legal compliance.',
    'icon': LucideIcons.fileX,
    'color': const Color(0xFFEF4444),
    'category': 'Tax',
    'averageWorkingDays': '5–10 days',
    'features': ['Application for Cancellation', 'Final Return GSTR-10', 'Reply to Notices', 'Assessment Clearance', 'Cancellation Order'],
  },
  {
    'title': 'DPIIT Recognition',
    'subtitle': 'Get Startup India recognition with complete DPIIT registration support.',
    'description': 'Get Startup India recognition with complete DPIIT registration support.',
    'icon': HugeIcons.strokeRoundedRocket,
    'color': const Color(0xFF10B981),
    'category': 'Licensing',
    'averageWorkingDays': '5–7 days',
    'features': ['Pitch deck preparation', 'Tax Exemption Support', 'Priority Sector Lending Support', 'Government approval', 'IPR Fast Track'],
  },
  {
    'title': 'ISO Certification',
    'subtitle': 'Obtain ISO certification with documentation and audit support services.',
    'description': 'Obtain ISO certification with documentation and audit support services.',
    'icon': LucideIcons.award,
    'color': const Color(0xFF14B8A6),
    'category': 'Licensing',
    'averageWorkingDays': '5–7 days',
    'documentsRequired': ['Recent Invoice copy raised', 'Address Proof', 'Authorised Letter'],
    'features': ['ISO Certificate via Courier'],
  },
  {
    'title': 'FSSAI Registration',
    'subtitle': 'Register your food business and obtain the required FSSAI license.',
    'description': 'Register your food business and obtain the required FSSAI license.',
    'icon': LucideIcons.utensils,
    'color': const Color(0xFF10B981),
    'category': 'Licensing',
    'averageWorkingDays': '1–3 days',
      'documentsRequired': ['Company Incorporation documents', 'Proof of Business Address', 'NOC from Premises Owner'],
    'features': ['Basic/State/Central License', 'Food Safety Audit', 'Premise Inspection Support', 'Renewal Reminders', 'Product Category Mapping'],
  },
  {
    'title': 'DUNS Number',
    'subtitle': 'Obtain a D-U-N-S Number for global business identification and credibility.',
    'description': 'Obtain a D-U-N-S Number for global business identification and credibility.',
    'icon': LucideIcons.globe,
    'color': const Color(0xFF10B981),
    'category': 'Licensing',
    'averageWorkingDays': '1–3 days',
    'documentsRequired': ['Address Proof (Utility bill / Bank statement)', 'Company Incorporation & PAN'],
    'features': ['Mandatory Access to Tech Developer Programs', 'Creation of a Business Credit File', 'Global Vendor Onboarding (B2B Perks)', 'D&B Global Directory Listing'],
  },
  {
    'title': 'Import Export Code (IEC)',
    'subtitle': 'Import Export Code registration for cross-border trade.',
    'description': 'Import Export Code registration for cross-border trade.',
    'icon': LucideIcons.globe,
    'color': const Color(0xFF3B82F6),
    'category': 'Licensing',
    'averageWorkingDays': '1–3 days',
    'documentsRequired': ['Company Incorporation & PAN'],
    'features': ['Application Filing', 'DGFT Registration', 'Modification Support', 'Customs Clearance Help', 'IEC Certificate'],
  },
  {
    'title': 'BIS Certification',
    'subtitle': 'Obtain BIS certification for products meeting Indian quality standards.',
    'description': 'Obtain BIS certification for products meeting Indian quality standards.',
    'icon': LucideIcons.shieldCheck,
    'color': const Color(0xFFF59E0B),
    'category': 'Licensing',
    'averageWorkingDays': '30–90 days',
    'features': ['Product Testing', 'Factory Inspection', 'Application Filing', 'Grant of License', 'Renewal Support'],
  },
  {
    'title': 'CE Certification',
    'subtitle': 'Meet regulatory certification requirements before product launch.',
    'description': 'Meet regulatory certification requirements before product launch.',
    'icon': LucideIcons.checkCircle,
    'color': const Color(0xFF14B8A6),
    'category': 'Licensing',
    'averageWorkingDays': '5–7 days',
    'features': ['Documentation Preparation', 'Testing Coordination', 'Compliance Audit', 'Declaration of Conformity', 'Certification Grant'],
  },
  {
    'title': 'RoHS Certification',
    'subtitle': 'Obtain RoHS certification for products meeting hazardous substance regulations.',
    'description': 'Obtain RoHS certification for products meeting hazardous substance regulations.',
    'icon': LucideIcons.checkCircle,
    'color': const Color(0xFF14B8A6),
    'category': 'Licensing',
    'averageWorkingDays': '5–7 days',
    'features': ['Documentation Preparation', 'Testing Coordination', 'Compliance Audit', 'Declaration of Conformity', 'Certification Grant'],
  },
  {
    'title': 'LEI Registration',
    'subtitle': 'Obtain a Legal Entity Identifier for financial and banking transactions.',
    'description': 'Obtain a Legal Entity Identifier for financial and banking transactions.',
    'icon': LucideIcons.barcode,
    'color': const Color(0xFF6366F1),
    'category': 'Licensing',
    'averageWorkingDays': '1–3 days',
    'features': ['LEI Application', 'Global Directory Listing', 'Renewal Management', 'Data Validation', 'LEI Code Generation'],
  },
  {
    'title': 'Digital Signature Certificate (DSC)',
    'subtitle': 'Digital Signature Certificate for individuals & organizations.',
    'description': 'Digital Signature Certificate for individuals & organizations.',
    'icon': LucideIcons.usb,
    'color': const Color(0xFF8B5CF6),
    'category': 'Licensing',
    'averageWorkingDays': '1–2 days',
    'documentsRequired': ['Aadhar & PAN Card'],
    'features': ['Application Processing', 'Video Verification', 'KYC Verification', 'Token Procurement', '2-Year Validity'],
  }
];
