import 'package:flutter/material.dart';
import 'package:hugeicons/hugeicons.dart';
import 'package:lucide_icons_flutter/lucide_icons.dart';

final List<Map<String, dynamic>> kAvailableServices = [
  // --- Incorporation ---
  {
    'title': 'Private Limited Incorporation',
    'subtitle': 'Full-scale incorporation service including name reservation, DSC, DIN, MOA/AOA.',
    'description': 'Full-scale incorporation service including name reservation, DSC, DIN, MOA/AOA.',
    'icon': HugeIcons.strokeRoundedOffice,
    'color': const Color(0xFF6366F1),
    'category': 'Incorporation',
    'features': ['Name Reservation (RUN)', 'Digital Signature (DSC)', 'Director Identification (DIN)', 'MOA & AOA Drafting', 'Certificate of Incorporation'],
  },
  {
    'title': 'LLP Incorporation',
    'subtitle': 'Statutory compliance for Limited Liability Partnerships.',
    'description': 'Statutory compliance for Limited Liability Partnerships.',
    'icon': HugeIcons.strokeRoundedBriefcase01,
    'color': const Color(0xFFF59E0B),
    'category': 'Incorporation',
    'features': ['Digital Signature Certificate (DSC)', 'Form 8 Statement of Account', 'Form 11 Annual Return', 'DIR-3 KYC of Partners', 'Income Tax Return Filing', 'LLP Agreement Maintenance'],
  },
  {
    'title': 'OPC',
    'subtitle': 'One Person Company registration for solo entrepreneurs.',
    'description': 'One Person Company registration for solo entrepreneurs.',
    'icon': HugeIcons.strokeRoundedUser,
    'color': const Color(0xFF10B981),
    'category': 'Incorporation',
    'features': ['Name Reservation', 'DSC & DIN', 'MOA & AOA Drafting', 'Certificate of Incorporation', 'Bank Setup Support'],
  },
  {
    'title': 'Proprietorship',
    'subtitle': 'Sole vendor formation with business identification.',
    'description': 'Sole vendor formation with business identification.',
    'icon': HugeIcons.strokeRoundedUser,
    'color': const Color(0xFF3B82F6),
    'category': 'Incorporation',
    'features': ['Document support', 'MSME/Udyam Registration', 'GST Registration', 'Bank Account Assistance'],
  },
  {
    'title': 'MSME',
    'subtitle': 'Official Udyam Registration for small and medium enterprises.',
    'description': 'Official Udyam Registration for small and medium enterprises.',
    'icon': LucideIcons.medal,
    'color': const Color(0xFFF59E0B),
    'category': 'Incorporation',
    'features': ['Udyam Registration Certificate', 'Priority Sector Lending Support', 'Govt Subsidy Assistance', 'Collateral Free Loan Support', 'IP Reimbursement Advisory'],
  },

  // --- Compliance ---
  {
    'title': 'MCA Compliance',
    'subtitle': 'Annual return filings and MCA statutory compliance.',
    'description': 'Annual return filings and MCA statutory compliance.',
    'icon': HugeIcons.strokeRoundedTask01,
    'color': const Color(0xFF14B8A6),
    'category': 'Compliance',
    'features': ['Auditor appointment', '360° Accounting & Bookkeeping', 'Statutory Auditing', 'AOC 4 & MGT 7 filing', 'Director KYC', 'AGM & Notice', 'ITR filing'],
  },
  {
    'title': 'TDS',
    'subtitle': 'TDS return filing and certificate issuance.',
    'description': 'TDS return filing and certificate issuance.',
    'icon': HugeIcons.strokeRoundedCalculator,
    'color': const Color(0xFF8B5CF6),
    'category': 'Compliance',
    'features': ['TDS Computation', 'Quarterly Return Filing', 'Form 16/16A Generation', 'Challan Payment', 'Notice Reply'],
  },
  {
    'title': 'PF',
    'subtitle': 'Provident Fund registration and monthly compliance.',
    'description': 'Provident Fund registration and monthly compliance.',
    'icon': HugeIcons.strokeRoundedDocumentValidation,
    'color': const Color(0xFF3B82F6),
    'category': 'Compliance',
    'features': ['PF Registration', 'Monthly ECR Filing', 'Challan Generation', 'Employee Addition/Deletion', 'KYC Updates'],
  },

  // --- IP ---
  {
    'title': 'Trade Mark',
    'subtitle': 'Brand protection and intellectual property rights.',
    'description': 'Brand protection and intellectual property rights.',
    'icon': HugeIcons.strokeRoundedTradeMark,
    'color': const Color(0xFFEC4899),
    'category': 'IP',
    'features': ['Trademark Search', 'Application Filing', 'Objection Handling', 'Hearing Support', 'Registration Certificate', 'Reimbursement Advisory'],
  },
  {
    'title': 'Copyright',
    'subtitle': 'Protection for original creative literary or artistic works.',
    'description': 'Protection for original creative literary or artistic works.',
    'icon': LucideIcons.copyright,
    'color': const Color(0xFF6366F1),
    'category': 'IP',
    'features': ['Diary Number Generation', 'Application Filing', 'Work Submission', 'Objection Reply', 'Copyright Certificate'],
  },
  {
    'title': 'Patent',
    'subtitle': 'Exclusive rights for your inventions.',
    'description': 'Exclusive rights for your inventions.',
    'icon': LucideIcons.lightbulb,
    'color': const Color(0xFFF59E0B),
    'category': 'IP',
    'features': ['Patent Search', 'Provisional Drafting', 'Complete Specification', 'Examination Reply', 'Patent Grant'],
  },

  // --- Tax ---
  {
    'title': 'GST Registration',
    'subtitle': 'GST Registration for your business! Thank you for choosing Wealth Empires.',
    'description': 'GST Registration for your business! Thank you for choosing Wealth Empires.',
    'icon': HugeIcons.strokeRoundedLicenseDraft,
    'color': const Color(0xFF10B981),
    'category': 'Tax',
    'features': ['GST Application Filing', 'Document Verification', 'ARN Generation', 'Clarification Support', 'GSTIN Certificate'],
  },
  {
    'title': 'GST filing',
    'subtitle': 'Monthly/Quarterly GST returns and reconciliations.',
    'description': 'Monthly/Quarterly GST returns and reconciliations.',
    'icon': HugeIcons.strokeRoundedCalculate,
    'color': const Color(0xFF3B82F6),
    'category': 'Tax',
    'features': ['GSTR-1 & 3B Filing', 'GSTR-2A/2B Reconciliation', 'Input Tax Credit (ITC)', 'Annual Return GSTR-9', 'Audit Support'],
  },
  {
    'title': 'GST Cancelation',
    'subtitle': 'Surrender and cancel your GST registration.',
    'description': 'Surrender and cancel your GST registration.',
    'icon': LucideIcons.fileX,
    'color': const Color(0xFFEF4444),
    'category': 'Tax',
    'features': ['Application for Cancellation', 'Final Return GSTR-10', 'Reply to Notices', 'Assessment Clearance', 'Cancellation Order'],
  },
  {
    'title': 'ITR',
    'subtitle': 'Income Tax Return filing for individuals and businesses.',
    'description': 'Income Tax Return filing for individuals and businesses.',
    'icon': HugeIcons.strokeRoundedCalculate,
    'color': const Color(0xFF8B5CF6),
    'category': 'Tax',
    'features': ['Income Computation', 'Tax Saving Advisory', 'Return Filing (ITR 1-7)', 'Refund Tracking', 'Assessment Support'],
  },

  // --- Licensing ---
  {
    'title': 'DUNS',
    'subtitle': 'Data Universal Numbering System for global business identity.',
    'description': 'Data Universal Numbering System for global business identity.',
    'icon': LucideIcons.globe,
    'color': const Color(0xFF10B981),
    'category': 'Licensing',
    'features': ['Global Business Identity Card', 'Mandatory Access to Tech Developer Programs', 'Creation of a Business Credit File', 'Global Vendor Onboarding (B2B Perks)', 'D&B Global Directory Listing'],
  },
  {
    'title': 'DPIIT',
    'subtitle': 'Startup India Certification for your startup! Please provide your details correctly.',
    'description': 'Startup India Certification for your startup! Please provide your details correctly.',
    'icon': HugeIcons.strokeRoundedRocket,
    'color': const Color(0xFF10B981),
    'category': 'Licensing',
    'features': ['Pitch deck preparation', 'Tax Exemption Support', 'Priority Sector Lending Support', 'Government approval', 'IPR Fast Track'],
  },
  {
    'title': 'ISO',
    'subtitle': 'Quality management certification (ISO 9001 and others).',
    'description': 'Quality management certification (ISO 9001 and others).',
    'icon': LucideIcons.award,
    'color': const Color(0xFF14B8A6),
    'category': 'Licensing',
    'features': ['Process Audit', 'Quality Manual', 'Certification Support', 'Annual Surveillance', 'Training'],
  },
  {
    'title': 'BIS',
    'subtitle': 'Bureau of Indian Standards product certification.',
    'description': 'Bureau of Indian Standards product certification.',
    'icon': LucideIcons.shieldCheck,
    'color': const Color(0xFFF59E0B),
    'category': 'Licensing',
    'features': ['Product Testing', 'Factory Inspection', 'Application Filing', 'Grant of License', 'Renewal Support'],
  },
  {
    'title': 'RoHS',
    'subtitle': 'European standard certifications for electronics and products.',
    'description': 'European standard certifications for electronics and products.',
    'icon': LucideIcons.checkCircle,
    'color': const Color(0xFF14B8A6),
    'category': 'Licensing',
    'features': ['Documentation Preparation', 'Testing Coordination', 'Compliance Audit', 'Declaration of Conformity', 'Certification Grant'],
  },
  {
    'title': 'CE',
    'subtitle': 'European standard certifications for electronics and products.',
    'description': 'European standard certifications for electronics and products.',
    'icon': LucideIcons.checkCircle,
    'color': const Color(0xFF14B8A6),
    'category': 'Licensing',
    'features': ['Documentation Preparation', 'Testing Coordination', 'Compliance Audit', 'Declaration of Conformity', 'Certification Grant'],
  },
  {
    'title': 'FSSAI',
    'subtitle': 'Registration for food business operators, manufacturers, and startups.',
    'description': 'Registration for food business operators, manufacturers, and startups.',
    'icon': LucideIcons.utensils,
    'color': const Color(0xFF10B981),
    'category': 'Licensing',
    'features': ['Basic/State/Central License', 'Food Safety Audit', 'Premise Inspection Support', 'Renewal Reminders', 'Product Category Mapping'],
  },
  {
    'title': 'IE Code',
    'subtitle': 'Import Export Code registration for cross-border trade.',
    'description': 'Import Export Code registration for cross-border trade.',
    'icon': LucideIcons.globe,
    'color': const Color(0xFF3B82F6),
    'category': 'Licensing',
    'features': ['Application Filing', 'DGFT Registration', 'Modification Support', 'Customs Clearance Help', 'IEC Certificate'],
  },
  {
    'title': 'LEI',
    'subtitle': 'Legal Entity Identifier registration for financial transactions.',
    'description': 'Legal Entity Identifier registration for financial transactions.',
    'icon': LucideIcons.barcode,
    'color': const Color(0xFF6366F1),
    'category': 'Licensing',
    'features': ['LEI Application', 'Global Directory Listing', 'Renewal Management', 'Data Validation', 'LEI Code Generation'],
  },
  {
    'title': 'DSC',
    'subtitle': 'Digital Signature Certificate for individuals & organizations.',
    'description': 'Digital Signature Certificate for individuals & organizations.',
    'icon': LucideIcons.usb,
    'color': const Color(0xFF8B5CF6),
    'category': 'Licensing',
    'features': ['Application Processing', 'Video Verification', 'KYC Verification', 'Token Procurement', '2-Year Validity'],
  }
];
